//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class nl_NL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nl_NL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challenge1.Resources.nl-NL", typeof(nl_NL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start nieuw spel.
        /// </summary>
        public static string MainWindowViewModel_button_new_game {
            get {
                return ResourceManager.GetString("MainWindowViewModel_button_new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start spel.
        /// </summary>
        public static string MainWindowViewModel_button_start_game {
            get {
                return ResourceManager.GetString("MainWindowViewModel_button_start_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaar om the spelen! Gebruik de pijltoetsen of [W,S,A,D] om the bewegen. Jij bent P, je moet naar E gaan zonder dat D jou weet te vinden!.
        /// </summary>
        public static string MainWindowViewModel_info_ready_game {
            get {
                return ResourceManager.GetString("MainWindowViewModel_info_ready_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spel aan het voorbereiden.
        /// </summary>
        public static string MainWindowViewModel_info_setting_game {
            get {
                return ResourceManager.GetString("MainWindowViewModel_info_setting_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeilijkheid:.
        /// </summary>
        public static string MainWindowViewModel_label_maze_difficulty {
            get {
                return ResourceManager.GetString("MainWindowViewModel_label_maze_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoogte:.
        /// </summary>
        public static string MainWindowViewModel_label_maze_height {
            get {
                return ResourceManager.GetString("MainWindowViewModel_label_maze_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doolhof breedte:.
        /// </summary>
        public static string MainWindowViewModel_label_maze_width {
            get {
                return ResourceManager.GetString("MainWindowViewModel_label_maze_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speler naam:.
        /// </summary>
        public static string MainWindowViewModel_label_player_name {
            get {
                return ResourceManager.GetString("MainWindowViewModel_label_player_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doolhof gemaakt.
        /// </summary>
        public static string MainWindowViewModel_rest_created_maze {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_created_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doolhof aan het maken.
        /// </summary>
        public static string MainWindowViewModel_rest_creating_maze {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_creating_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doolhof ophalen.
        /// </summary>
        public static string MainWindowViewModel_rest_get_maze {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_get_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doolhof vernieuwen.
        /// </summary>
        public static string MainWindowViewModel_rest_updating_maze {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_updating_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop in richting.
        /// </summary>
        public static string MainWindowViewModel_rest_walk_direction {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_walk_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het pony spel.
        /// </summary>
        public static string MainWindowViewModel_window_title {
            get {
                return ResourceManager.GetString("MainWindowViewModel_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeilijkheid moet een getal zijn..
        /// </summary>
        public static string MainWindowViewModel_wrong_difficulty {
            get {
                return ResourceManager.GetString("MainWindowViewModel_wrong_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeilijkheid moet tussen de 0 en de 10 liggen..
        /// </summary>
        public static string MazeParams_wrong_difficulty {
            get {
                return ResourceManager.GetString("MazeParams_wrong_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoogte moet tussen de 15 en 25 zitten..
        /// </summary>
        public static string MazeParams_wrong_height {
            get {
                return ResourceManager.GetString("MazeParams_wrong_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breedte moet tussen de 15 en 25 zitten..
        /// </summary>
        public static string MazeParams_wrong_width {
            get {
                return ResourceManager.GetString("MazeParams_wrong_width", resourceCulture);
            }
        }
    }
}
