//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pony.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pony.Resources.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始新游戏.
        /// </summary>
        public static string MainWindowViewModel_button_new_game {
            get {
                return ResourceManager.GetString("MainWindowViewModel_button_new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始游戏.
        /// </summary>
        public static string MainWindowViewModel_button_start_game {
            get {
                return ResourceManager.GetString("MainWindowViewModel_button_start_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 准备开始！使用[上，下，左，右]键头或[W，S，A，D]键移动。 您是P， 请到达E，但不要让D找到您！.
        /// </summary>
        public static string MainWindowViewModel_info_ready_game {
            get {
                return ResourceManager.GetString("MainWindowViewModel_info_ready_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置游戏。。.
        /// </summary>
        public static string MainWindowViewModel_info_setting_game {
            get {
                return ResourceManager.GetString("MainWindowViewModel_info_setting_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏难度：.
        /// </summary>
        public static string MainWindowViewModel_label_maze_difficulty {
            get {
                return ResourceManager.GetString("MainWindowViewModel_label_maze_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 迷宫高度：.
        /// </summary>
        public static string MainWindowViewModel_label_maze_height {
            get {
                return ResourceManager.GetString("MainWindowViewModel_label_maze_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 迷宫宽度：.
        /// </summary>
        public static string MainWindowViewModel_label_maze_width {
            get {
                return ResourceManager.GetString("MainWindowViewModel_label_maze_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选手姓名：.
        /// </summary>
        public static string MainWindowViewModel_label_player_name {
            get {
                return ResourceManager.GetString("MainWindowViewModel_label_player_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 迷宫创建成功.
        /// </summary>
        public static string MainWindowViewModel_rest_created_maze {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_created_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在创建迷宫.
        /// </summary>
        public static string MainWindowViewModel_rest_creating_maze {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_creating_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检索迷宫.
        /// </summary>
        public static string MainWindowViewModel_rest_get_maze {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_get_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新迷宫.
        /// </summary>
        public static string MainWindowViewModel_rest_updating_maze {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_updating_maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行走方向 .
        /// </summary>
        public static string MainWindowViewModel_rest_walk_direction {
            get {
                return ResourceManager.GetString("MainWindowViewModel_rest_walk_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小马游戏.
        /// </summary>
        public static string MainWindowViewModel_window_title {
            get {
                return ResourceManager.GetString("MainWindowViewModel_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 难度必须是数字。.
        /// </summary>
        public static string MainWindowViewModel_wrong_difficulty {
            get {
                return ResourceManager.GetString("MainWindowViewModel_wrong_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 难度必须在0到10之间。.
        /// </summary>
        public static string MazeParams_wrong_difficulty {
            get {
                return ResourceManager.GetString("MazeParams_wrong_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高度必须在15到25之间。.
        /// </summary>
        public static string MazeParams_wrong_height {
            get {
                return ResourceManager.GetString("MazeParams_wrong_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宽度必须在15到25之间。.
        /// </summary>
        public static string MazeParams_wrong_width {
            get {
                return ResourceManager.GetString("MazeParams_wrong_width", resourceCulture);
            }
        }
    }
}
